color: null
fieldLayouts:
  100c0c0e-ded8-4395-b294-91acbf7ae80c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-11T17:39:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 957da7cc-2190-4d55-96c9-e44bd35cd836
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T17:40:33+00:00'
            elementCondition: null
            fieldUid: 4f49f8d6-fcea-4d93-bd5f-2f1a69f5e749 # Body Text
            handle: description
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7601ef0f-4ea7-49a1-b17a-2b1f63ea6bb4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d4d24683-657b-4c7b-b7c5-a3718f9a3626
        userCondition: null
handle: faq
hasTitleField: true
icon: ''
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
